APPLY_FIXES: none 
ENABLE:
  - YAML
ENABLE_LINTERS:
  - YAML_V8R
DISABLE_LINTERS:
  - YAML_PRETTIER
  - YAML_YAMLLINT
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
YAML_V8R_FILE_EXTENSIONS:
  - ".meta"
YAML_V8R_PRE_COMMANDS:
  - command: echo "before parse"