APPLY_FIXES: none 
ENABLE:
  - YAML
ENABLE_LINTERS:
  - YAML_V8R
  - YAML_YAMLLINT
DISABLE_LINTERS:
  - YAML_PRETTIER
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
PRINT_ALPACA : false
LINTER_RULES_PATH: linter_rules/
SHOW_SKIPPED_LINTERS: false
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
YAML_V8R_ARGUMENTS: "-s https://github.com/VildaFaust/ReviewDogGitlabIntegration/blob/main/schema.json"
YAML_V8R_FILE_EXTENSIONS:
  - ".meta"